### ISSUE TITLE
Installation and set up the pipeline

### ISSUE THREAD

**Issue by hosseinfani** [fani-lab/ReQue#1]

**Comment by BhavyaPatel305** [comment]
Hello, **I am using **Windows**
I was trying to run this command: conda env create -f environment.yml
But I guess since I didn't had Anaconda installed, I was getting error
But after installing, I am still getting error
I tried to look up on internet, on stack overflow they are asking to configure path of anaconda but I am not sure what excatly I should do
Can you please help?

**Comment by hosseinfani** [comment]
@BhavyaPatel305 
Can you please send the error you receive here?

**Comment by BhavyaPatel305** [comment]
![Error](https://user-images.githubusercontent.com/93842768/201409364-3649a1d7-238b-44de-9cdb-199aee45ae29.jpg)

**Comment by BhavyaPatel305** [comment]
Also should I send email to Tim Brunet again to remind him or you will send it ?

**Comment by hosseinfani** [comment]
> ![Error](https://user-images.githubusercontent.com/93842768/201409364-3649a1d7-238b-44de-9cdb-199aee45ae29.jpg)
> 
> But I have already installed Anaconda to my local machine
> 
> But I guess I need to configure path, which I am not sure

do this in anaconda prompt. it's in the list of tools when you install anaconda

**Comment by hosseinfani** [comment]
> Also should I send email to Tim Brunet again to remind him or you will send it ?

I'll do that

**Comment by BhavyaPatel305** [comment]
Yes, that worked.

**Comment by BhavyaPatel305** [comment]
Hi, In video you are asking to download anserini and trec_eval but you are not showing how to do it
Can you please explain how should I download anserini?

**Comment by hosseinfani** [comment]
@BhavyaPatel305 
I believe you can find it yourself. Follow the links in readme!

**Comment by BhavyaPatel305** [comment]
Hi, I am sorry the button was right up there 
So I have downloaded:
1: FastText
2: GloVe

But When I am trying to click on 
![image](https://user-images.githubusercontent.com/93842768/201494821-b4a1e638-0e69-4862-8489-22f597e7616e.png)
It shows me this:
![image](https://user-images.githubusercontent.com/93842768/201494845-8586f27d-d11c-4340-8158-bc3d1d0938f9.png)

**Comment by BhavyaPatel305** [comment]
Hi, I have installed Anserini and trec_eval
I have indexed anserini using these commands
![image](https://user-images.githubusercontent.com/93842768/201496380-cf3ac84b-197c-478a-bf9d-3ae0304c7728.png)

So Basically I am at this part of video:

![image](https://user-images.githubusercontent.com/93842768/201496371-7a7a3b75-a3ef-4411-afb8-84247a2db45b.png)

But here you are using **/data/anserini**

For me this command is not working:
![image](https://user-images.githubusercontent.com/93842768/201496451-51e69314-c11d-4cbe-8a7e-b4d2982e56af.png)

I think this is because I am using **Windows** may be: **Can you tell what mistake I am making?**

**Comment by hosseinfani** [comment]
@BhavyaPatel305 
You don't need to do so as we have the indexes in our internal ms-teams at Query Refinement >> Files >> Indexes.
You can start with robust04 for now.

In your command prompt, you have to use correct address. In the video, I said I have the indexes in my server at /data folder. You have to see where you want to put the indexes and put that address.

Please do not blindly follow the instructions :))

**Comment by BhavyaPatel305** [comment]
Hello, 
I was trying to index the files but it is becomming really confusing for me 
It's like I don't know what do next after this:
![image](https://user-images.githubusercontent.com/93842768/202861653-d3523c69-1fa4-41c1-85df-298eb9f27fee.png)



My own pc:
![image](https://user-images.githubusercontent.com/93842768/202861685-16c64a92-2474-4229-95a6-7d2b1b7ae35f.png)


This part of video:
![image](https://user-images.githubusercontent.com/93842768/202861631-e78784a2-656b-4b29-885a-ec1c4aaa1d43.png)

Are you available on Monday after DBMS class?

**Comment by hosseinfani** [comment]
@BhavyaPatel305 
Forget about indexes. I asked you to install anserini in its folder. Could you do that?

**Comment by BhavyaPatel305** [comment]
Yes
![image](https://user-images.githubusercontent.com/93842768/202868696-d052e77b-0985-4cc5-80c5-b941093f9679.png)

**Comment by hosseinfani** [comment]
@BhavyaPatel305 
this is the source in java. you have to build it. In the bin folder, you should have appassembler folder after.

**Comment by BhavyaPatel305** [comment]
Hello, Build was successful
![image](https://user-images.githubusercontent.com/93842768/203125225-2d496ff9-230d-40f2-a367-b96dd8a7243f.png)

And now in anserini folder I can see files such as target etc
![image](https://user-images.githubusercontent.com/93842768/203125351-8226580f-4e24-466f-9ff2-911f87f9c4e8.png)


But in bin folder I don't see any file as appassembler
![image](https://user-images.githubusercontent.com/93842768/203125441-e3926a3c-2983-430a-ab56-0af81956ab4a.png)


What should I do?

**Comment by hosseinfani** [comment]
@BhavyaPatel305 
Sorry, I meant  `\target\appassembler\bin`

**Comment by BhavyaPatel305** [comment]
To get the appassembler folder you need to build it separately
![image](https://user-images.githubusercontent.com/93842768/203375988-bfece8df-cf8e-442e-95be-bda7cba54d49.png)

**Comment by BhavyaPatel305** [comment]
@hosseinfani 
Even after installing the required mingw packages for netbeans to recognise MAKE file 

It is still not recognising it
![image](https://user-images.githubusercontent.com/93842768/203377157-eca83143-081a-43c3-b3ad-c1f0372d7496.png)

Do you have any suggestion?

**Comment by BhavyaPatel305** [comment]
@hosseinfani 
Hi, I came to your lab at 2 pm but it was locked

**Comment by hosseinfani** [comment]
Hi @BhavyaPatel305 ,
I have no update on this task since Nov. Are you still interested in working in our lab?

**Comment by BhavyaPatel305** [comment]
Hi, so after we tried installing some extensions in your office hours
you asked me to run make file

But the problem is even after adding extensions, it is still not recognising MAKE file

![image](https://user-images.githubusercontent.com/93842768/211665362-0c3d590e-a0fb-4c45-baf1-3e79e6c1ec1d.png)

**Comment by BhavyaPatel305** [comment]
Hi, I guess now it works although still it does not recognize MAKE file

but I tried to do this
![image](https://user-images.githubusercontent.com/93842768/211698633-4a131ac5-a537-4562-bfa8-64226b52d8b8.png)

Here it gave me error that, there is nothing like pyserini

so I tried to run this command 

pip install pyserini

but doing that gives me(Build failed)

![image](https://user-images.githubusercontent.com/93842768/211698889-977140b7-c698-46d4-80ed-83351d562870.png)

and then eventually I have to stop it using ctrl + C



So now our main problem is pyserini

I guess then everything should work well

Do you suggest anything?

**Comment by hosseinfani** [comment]
@BhavyaPatel305 look at their github and the issue pages there. There should be some help: https://github.com/castorini/pyserini

**Comment by BhavyaPatel305** [comment]
I found a helpful comment on this, so just posting here just in case if next person needs it

https://github.com/nmslib/nmslib/issues/464

**Comment by BhavyaPatel305** [comment]
@hosseinfani Hi, I was thinking that if possible could we just do like where say for example you have 1 copy of this whole program properly set up and running

So what we can do is you can just may be zip it and give it to someone who is installing this software

because I noticed that in the installation process we are just trying to download the files for eval and other folders (just simple file downloads)

But if say you just provide say a zip file where all these files are already downloaded there would be many steps which can be cut up

What do you think?

I am rn stuck at the same problem above 

If possible can I meet you tommorrow?

**Comment by hosseinfani** [comment]
@BhavyaPatel305 
in future we can do that, that is, delivering a software bundle. But this is not our priority now. This week I'm very busy but will be in lab most of the time. See you there.

**Comment by hosseinfani** [comment]
Hi @BhavyaPatel305 
Hope you're doing great. 
It's been a while and there is no update on this task. I think you're busy with courses and cannot find time to work on this project. I understand.
For now, we can stop our collaboration until you have lower course work at the school. Hopefully, in future we can continue. 

Best,
hf
